### ISSUE TITLE
Add scala-native support

### ISSUE THREAD

**Issue by kevinwright** [sbt/sbt-projectmatrix#15]
Looks like it could make my life a lot easier... unfortunately I also need to cross-compile to scala-native

**Comment by exoego** [comment]
I opened a WIP PR https://github.com/sbt/sbt-projectmatrix/pull/12 for scala-native support, but stucked.
Since I have only very limited experience in scala-native, it would be helpful if someone give me advice or turn over PR.

**Comment by kevinwright** [comment]
Oh nice... I'll kick the tyres and see if I can get it to behave

**Comment by kevinwright** [comment]
That was easy!
Remove any references to scala 2.12 in the native tests and it passes just fine.  I flagged anywhere I could see one against the PR

At the time of writing, scala-native only exists for scala 2.11
