### ISSUE TITLE
Coordinating on matrix functionality…

### ISSUE THREAD

**Issue by djspiewak** [sbt/sbt-projectmatrix#2]
Note to self: <kbd>Tab</kbd> is not <kbd>Return</kbd>. Sorry. Issue description incoming via edits…

---

While I like the functionality this plugin offers (effectively, improved cross-building), it falls very short of a true matrix build of the style that you can get with Travis and such. The reason for this is varying dependencies and the need to encode the matrix instancing in the published versions.  For an example of this, see [djspiewak/smock](https://github.com/djspiewak/smock)

Smock gets cross-built against 2.11 and 2.12, as well as like four different versions of specs2, one of which doesn't exist on 2.12. The version of specs2 is encoded as a qualifier in the published version (e.g. `smock_2.12-0.4.0-specs2-4.2.0`), and all of the version publication and matrixing is controlled via the `release` command alias. Travis builds are compatible with this and can drive the matrix selection via an environment variable.

[typelevel/cats](https://github.com/typelevel/cats) also has a similar problem right now publishing for 2.13-M4, since cats is published for 2.10/2.11/2.12 and has a dependency on typelevel/discipline, which itself has a dependency on scalacheck. Scalacheck doesn't have a single version which has been published for 2.10/2.11/2.12/2.13-M4, since they dropped compatibility with 2.10 in the same release which added compatibility for 2.13-M4. So that necessitates a similar cascade of matrixing.

None of this style of thing is really supported by sbt-projectmatrix. Not that the functionality here is bad or even incomplete in a real sense, but it does fall short of actually being a build matrix in the sense that the ecosystem really needs. I look at this more as a generalization of cross-building which is natural and meets the same restricted use-case.

Anyway… my thought on all this is that I'm going to develop a new plugin which addresses this niche: full support for matrixed settings and corresponding version qualifiers. The reason I'm posting this issue is because I was *also* planning on calling this a project/build/something matrix and using setting keys and names along those lines, but that becomes extremely difficult both conceptually and practically if SBT itself (i.e. 1.2.0-RC3) is using those names. So I'm interested as to your thoughts on this.

On the one hand, a name is a name. But on the other hand, I feel like people looking for Travis-style build matrixing are going to end up at `projectMatrix` and be disappointed. And similarly, projects such as mine which seek to implement more general matrixing are going to end up with confusing messaging, since the term effectively gets redefined by the `projectMatrix` identifier in SBT 1.2.0.

Thoughts?

**Comment by djspiewak** [comment]
Updated this with description. Bumping for notifications. Sorry again for the misclick.

**Comment by eed3si9n** [comment]
sbt-projectmatrix supports cross building by library variance. See https://github.com/sbt/sbt-projectmatrix/blob/master/src/sbt-test/projectMatrix/custom/build.sbt

In that example, I am building 2.11 and 2.12 with two different versions of Typesafe Config.

I can try to document it in the readme or surface that with better name than `.custom(...)`.

**Comment by djspiewak** [comment]
Ah interesting, that does indeed resolve the issue. More conventionally, such cross-builds are denoted by version qualifiers (like what smock does) rather than artifact qualifiers (as in your example), but that's easily accomplished. I would definitely document it in the readme, since this is actually considerably more widely-needed functionality than the module-specific `crossScalaVersions`.
