### ISSUE TITLE
Per-configuration classpath dependencies

### ISSUE THREAD

**Issue by hugo-vrijswijk** [sbt/sbt-projectmatrix#22]
I want to have a configuration similar to https://www.scala-sbt.org/1.x/docs/Multi-Project.html#Per-configuration+classpath+dependencies

So that I can use test setup files of projectA in projectB.

When creating a setup similar to it, sbt gives the following error:

```
build.sbt:19: error: value % is not a member of sbt.internal.ProjectMatrix
  .dependsOn(projectA, projectA % "test->test")
```

Is there any way to realize the described setup?

**Comment by eed3si9n** [comment]
I am sending a PR for this.
