### ISSUE TITLE
Support intellij import

### ISSUE THREAD

**Issue by OlegYch** [sbt/sbt-projectmatrix#25]
Unfortunately it looks like fix for #3 broke import in intellij.
With 0.5.0 imported project looks like this:
![image](https://user-images.githubusercontent.com/268312/80485237-b03f6880-8961-11ea-9661-8a1bb5b208ef.png)
With 0.5.1 idea complains about 
```
3:00 PM	Duplicate content roots detected
								Path [D:/Distrib/Coding/Java/scala/scastie/api] of module [apiJVM2_11] was removed from modules [apiJS2_13, apiJVM2_10, apiJVM2_12, apiJVM2_13]
								Also 1 more path was deduplicated. See idea log for details
```
and result looks like this:
![image](https://user-images.githubusercontent.com/268312/80485319-d5cc7200-8961-11ea-9f6f-ef2d6bb08117.png)
and cross-built module sources are not available in other modules

**Comment by OlegYch** [comment]
сс @jastice

**Comment by retronym** [comment]
👍 I'm trying to work on Zinc 1.4.x but running into this problem. Maybe for IntellIJ it would be better to just focus on a single instance?

@eed3si9n How could I configure sbt-project-matrix to add `SettingKey("ideSkipProject") := true` to all but the first project stamped off the template project?

**Comment by eed3si9n** [comment]
As a workaround maybe I could make some directories under a dot directory like `.sbt/matrix/fooJVM2_13` and use that as the base directory? That way the build users can ignore them.

> How could I configure sbt-project-matrix to add SettingKey("ideSkipProject") := true to all but the first project stamped off the template project?

I'm not sure if there's an easy way to say all-but-the-first-row, but I guess you could say

```scala
SettingKey("ideSkipProject") := scalaVersion.value.startsWith("2.12.")
```

**Comment by OlegYch** [comment]
> As a workaround maybe I could make some directories under a dot directory like `.sbt/matrix/fooJVM2_13` and use that as the base directory? That way the build users can ignore them.

that sounds good

**Comment by OlegYch** [comment]
@eed3si9n thanks, it works
(though deleting .idea and reimporting the project seems necessary)
