### ISSUE TITLE
Support multi-module projects without common scala version

### ISSUE THREAD

**Issue by erikvanoosten** [sbt/sbt-projectmatrix#27]
It would be great if this plugin could support multi-module projects where the different modules have no scala version in common.

In this situation something like `ThisBuild / scalaVersion := "???"` is not even possible.

For example, I am currently trying to maintain a project that has a core module that compiles for 2.11, 2.12 and 2.13. Then another module expands on that for spray (2.11 only), and another module that uses a modern http4s version (2.12 and 2.13).

**Comment by eed3si9n** [comment]
Aren't those the use case described in readme?
- https://github.com/sbt/sbt-projectmatrix#two-matrices
- https://github.com/sbt/sbt-projectmatrix#parallel-cross-library-building

**Comment by erikvanoosten** [comment]
I am afraid not. In both these cases, every module can be compiled with scala 2.12.8.

**Comment by keynmol** [comment]
I decided to check my understanding of projectmatrix. This seems to work:

```scala
lazy val core = projectMatrix
  .in(file("core"))
  .jvmPlatform(
    scalaVersions = Seq("2.11.12", "2.12.8", "2.13.3")
  )

lazy val spray = projectMatrix
  .in(file("spray"))
  .dependsOn(core)
  .jvmPlatform(
    scalaVersions = Seq("2.11.12")
  )
  .settings(
    libraryDependencies += "io.spray" % "spray-http_2.11" % "1.3.4"
  )

lazy val http4s = projectMatrix
  .in(file("http4s"))
  .dependsOn(core)
  .jvmPlatform(
    scalaVersions = Seq("2.12.8", "2.13.3")
  )
```

And running `scalaVersion` shows correct results:

```
[info] core2_11 / scalaVersion
[info]  2.11.12
[info] spray2_11 / scalaVersion
[info]  2.11.12
[info] core2_12 / scalaVersion
[info]  2.12.8
[info] http4s2_12 / scalaVersion
[info]  2.12.8
[info] core / scalaVersion
[info]  2.13.3
[info] http4s / scalaVersion
[info]  2.13.3
[info] scalaVersion
[info]  2.12.12
```

@erikvanoosten does this look similar to what you want to achieve? As long as all the modules are `projectMatrix` then it should just work.

And if I remove `2.11.12` from `core`'s list, then SBT blows up:

```
java.lang.RuntimeException: no rows were found in core matching ProjectRow(true, List(PlatformAxis(jvm,JVM,jvm), ScalaVersionAxis(2.11.12,2.11))): List(ProjectRow(true, List(PlatformAxis(jvm,JVM,jvm), ScalaVersionAxis(2.12.8,2.12))), ProjectRow(true, List(PlatformAxis(jvm,JVM,jvm), ScalaVersionAxis(2.13.3,2.13))))
```

**Comment by erikvanoosten** [comment]
@keynmol So as long as there is a module that overlaps all scala versions it works? That might work for my use case.

**Comment by keynmol** [comment]
I'm not sure what you mean.

For this setup to work it doesn't matter how many modules overlap over which Scala versions.

Given projectmatrix generates projects, it just needs to make sure that along all the axes (e.g. scalaVersion axis) your module dependencies are okay. 

When you do `dependsOn` on the projectMatrix, it will look at the module (say, core), and see that there are three versions exist:

* 2.11
* 2.12
* 2.13

And then it looks at the versions in the module (say, spray) and sees you've only defined

* 2.11

Because core supports 2.11, projectMatrix will create a dependency link `spray2_11 -dependsOn-> core2_11` (remember those are separate projects now).

And for http4s it'd be two links:

* `http4s2_12 -dependsOn-> core2_12`
* `http4s2_13 -dependsOn-> core2_13`

So really think of projectMatrix generating absolutely independent separate projects, and then if it's possible to build a dependency link between those independent projects, then it all works out

**Comment by keynmol** [comment]
From my understanding, this is very different from the way `scalaVersion/crossScalaVersions` works (without the plugin)

Which always caused issues where, say, my `core` was cross-built for 2.12 and 2.13 and `docs` wasn't working with 2.13, and all hell broke loose.

This helps change that, by generating different projects which have their own local settings, so you don't need to set global scala versions and global crossScalaVersions

**Comment by erikvanoosten** [comment]
@keynmol Ah, so it works when _every_ module is a matrix module.

**Comment by keynmol** [comment]
Yep. When you start thinking of those as totally separate projects (and `dependsOn` being overloaded to look into the "matrix" of your dependent and dependency module), then it's easier to grok. 

Regular `project.dependsOn` - I don't even know what it will do :) But I know for sure that it works when everything is a project matrix.

In fact, I've used it for things like 

* `core` cross-compiling to 5 different scala versions **and** 3 platforms (jvm, native, scalajs)
* `plugin` - depends on the core, but only on jvm and scala 2.12

And it worked swimmingly. The reason it worked was that `plugin` was defined **also** as a projectMatrix, but it had only 1 element - `(jvm, 2.12)`. And the right dependency was ensured.
 
Let me know if this helps with your original question - I believe that the nature of projectmatrix is the answer to your build configuration, and if it is - we can close this issue :)

**Comment by erikvanoosten** [comment]
I doubt that my IDE (IntelliJ) will accept such an advanced sbt config but for sure we can close this issue :)
