### ISSUE TITLE
The plugin creates empty folders for every project in the matrix

### ISSUE THREAD

**Issue by agemooij** [sbt/sbt-projectmatrix#3]
When executing any aggregate task on a multi-project build using the projectmatrix plugin, the plugin creates a whole series of empty directories in the project root directory, one for each "virtual" project using the full id.

So if I have a root project that aggregates sub-projects A (id = foo-a, base = file("a")), B, and C, and I configure them to cross-compile for 2.11 and 2.12, then the plugin will create the following directories:

- foo-aJVM2_11
- foo-aJVM2_12
- foo-bJVM2_11
- foo-bJVM2_12
- foo-cJVM2_11
- foo-cJVM2_12

These directories are completely empty and of course they produce a lot of unwanted noise.

**Comment by agemooij** [comment]
I've validated that this occurs immediately upon sbt (shell) startup and not as a side effect of running subsequent commands in the shell.

**Comment by LukaszByczynski** [comment]
is there any workaround for that issue ?  I mean, maybe there is a flag in sbt @eed3si9n

**Comment by kevinwright** [comment]
The problem would appear to be here:

https://github.com/sbt/sbt-projectmatrix/blob/master/src/main/scala/sbt/ProjectMatrix.scala#L146

I have no idea why we're specifying the non-existent directory `new sbt.File(childId).getAbsoluteFile` as the root for derived projects.  If nothing else, is is probably also the reason why IntelliJ hates projectmatrix builds so much.
