### ISSUE TITLE
Disabling project name simplification

### ISSUE THREAD

**Issue by thesamet** [sbt/sbt-projectmatrix#31]
In 0.6.0, project names are simplified such that `JVM` and `2_13` are no longer appended to project names One of the consequences is that in CI environments we would need to loop over an empty string to indicate 2.13: in [this example](https://github.com/scalapb/ScalaPB/blob/8fedba65bd92a2990d74c3272a2c2286bda83572/.github/workflows/test.yml#L12) we would have to replace 2_13 with an empty string, which is less telling of what it's actually going to do.

**Comment by eed3si9n** [comment]
I haven't tested this but I did add `def defaultAxes(axes: VirtualAxis*): ProjectMatrix` method on `ProjectMatrix`. So the following hopefully should work:

```scala
lazy val core = (projectMatrix in file("core"))
  .settings(
    name := "core"
  )
  .defaultAxes()
  .jvmPlatform(scalaVersions = Seq("2.13.3", "2.12.12"))
```

**Comment by thesamet** [comment]
Confirming that adding a call to `defaultAxes` brings back the old behavior. It would be nice if the previous behavior becomes the default again: it's a bit odd when creating matrixes that the JVM and 2.13 are represented as empty strings, and likely 2.13 wouldn't be a sane default when dotty is out.

**Comment by eed3si9n** [comment]
I can't predict how long it would take for Scala 3.0 to be the defacto standard, so I think picking 2.13 is overall better than having to type `2_13`, and as you've confirmed the build users can chose their own default Scala version using `.defaultAxes(...)`. To be a replacement of current `++` in sbt, I think we should try to avoid suffixes as much as possible as the out-of-box behavior.

**Comment by thesamet** [comment]
I've been successfully using `defaultAxes` for a while as I prefer the consistency that there's always a Scala version number appended to the name. I realize it's a personal preference and good with having the `defaultAxes` option, so closing the issue.
