### ISSUE TITLE
Scala 3.0.0-M1

### ISSUE THREAD

**Issue by adamw** [sbt/sbt-projectmatrix#33]
I'm not sure if this is due to sbt-projectmatrix, but I'm out of other ideas for now.

Switching the dotty version from `0.27.0-RC1` to `3.0.0-M1` causes the following error during resolution:

```
[error] (update) sbt.librarymanagement.ResolveException: Error downloading org.scala-lang:scala-library:3.0.0-M1
[error]   not found: https://repo1.maven.org/maven2/org/scala-lang/scala-library/3.0.0-M1/scala-library-3.0.0-M1.pom
```

Might this be something with sbt-projectmatrix? I was looking at cats-effect (which has ported), and the only difference I could spot was that they use sbt-crossproject.

**Comment by eed3si9n** [comment]
Locally it works for me - https://github.com/sbt/sbt-projectmatrix/pull/34

**Comment by adamw** [comment]
Thanks a lot for checking, must be something else on my side then. Sorry for the noise :)
