### ISSUE TITLE
Version 0.6.0 is available but not released?

### ISSUE THREAD

**Issue by arkban** [sbt/sbt-projectmatrix#38]
Our scala-steward found [0.6.0](https://dl.bintray.com/sbt/sbt-plugin-releases/com.eed3si9n/sbt-projectmatrix/scala_2.12/sbt_1.0/0.6.0/) of `sbt-projectmatric`, but it does not appear in the list of releases [on GitHub](https://github.com/sbt/sbt-projectmatrix/releases). What's in this new release?

**Comment by eed3si9n** [comment]
Sorry it seems like I blogged about it in August https://eed3si9n.com/parallel-cross-building-sandwich, but didn't push the tag until now.
