### ISSUE TITLE
Using scalaJS bundler together with projectmatrix doesn't work

### ISSUE THREAD

**Issue by martijnhoekstra** [sbt/sbt-projectmatrix#45]
I'm not entirely sure what "doesn't work" means exactly, but at the very least,

```
projectMatrix.in(file("location"))
  .enablePlugins(ScalaJSBundlerPlugin)
  .settings(
    libraryDependencies ++= List(
      "org.scalameta" %% "munit"            % "0.7.22" % "test",
      "org.scalameta" %% "munit-scalacheck" % "0.7.22" % "test")
  )
 .jsPlatform(scalaVersions = List(scala213Version))
```

doesn't run any tests.

**Comment by keynmol** [comment]
1. You'll need `testFrameworks += new TestFramework("munit.Framework")` to tell SBT which framework to use
2. You'll need `%%%` on dependencies to be picked up by Scala.js

Can you try those and see if it helps?

**Comment by martijnhoekstra** [comment]
I'm now no longer sure how anything else in my project worked in the past, which I'm absolutely positive it did.
