### ISSUE TITLE
publish to maven central instead of bintray

### ISSUE THREAD

**Issue by xuwei-k** [sbt/sbt-projectmatrix#47]
https://github.com/sbt/sbt/issues/6294
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by keynmol** [comment]
@eed3si9n I can do the build changes for this, assuming the secrets will be set up for sbt-ci-release to handle?

**Comment by eed3si9n** [comment]
Sure.
