### ISSUE TITLE
`ProjectMatrix` should probably be public

### ISSUE THREAD

**Issue by ruippeixotog** [sbt/sbt-projectmatrix#58]
I'm exploring making [PureConfig](https://github.com/pureconfig/pureconfig) to use this plugin as we'd like to have more flexibility on cross-compiling. However, we have quite a lot of subprojects and we have [generic helpers](https://github.com/pureconfig/pureconfig/blob/master/build.sbt#L36-L44) to customize project settings.

For this use case it would be helpful to use `ProjectMatrix` as an argument. Is there any reason why it lives in the `sbt.internal` package and is not exported elsewhere?

**Comment by eed3si9n** [comment]
Generally plugins should have their own package names, but for sbt-projectmatrix I wanted to work on it as an extension of sbt codebase. Generally `sbt.internal` is a signal that it will not maintain binary compatibility, so I can iterate quicker. Once it becomes part of sbt core, I guess I'll move some of the classes into the sbt package.

Until then, feel free to use the internal classes if you're ok that things may break in future versions.
