### ISSUE TITLE
customRow doesn't enable Scala.js/Scala Native plugins

### ISSUE THREAD

**Issue by keynmol** [sbt/sbt-projectmatrix#63]
I've spotted this a while back, but not until I tried to write a plugin that integrates with projectmatrix that it became a problem.

`jsPlatform` and `nativePlatform` enable the plugin on the projects explicitly: https://github.com/sbt/sbt-projectmatrix/blob/develop/src/main/scala/sbt/internal/ProjectMatrix.scala#L377-L386

But base case of `customRow` doesn't: https://github.com/sbt/sbt-projectmatrix/blob/develop/src/main/scala/sbt/internal/ProjectMatrix.scala#L477-L484

The problem is that when one wants to generate a large matrix (with custom `VirtualAxis`, you have to do `customRow(...axes, project => project.enablePlugins(ScalaJSPlugin))` or break it down to multiple calls to js/jvm/nativePlatform.

This gets hairier in plugins that are brought in and have no knowledge of whether Scala.js/Scala Native plugins are brought in the project.

Options here are:

1. In customRow, handle if virtualAxes contains `VirtualAxis.js` or `VirtualAxis.native`

2. Expose the reflection based `scalajsPlugin` and `nativePlugin` methods: https://github.com/sbt/sbt-projectmatrix/blob/develop/src/main/scala/sbt/internal/ProjectMatrix.scala#L477-L484

3. Add additional overloads for `jsPlatform/nativePlatform/jvmPlatform` that take a list of additional `VirtualAxis` values (like `customRow` does)

Option 1 seems like what as a user I would expect the plugin to do, but introducing it now is a behaviour change
Option 3 is the safest option, and can be used both in userland and in plugins
Option 2 is... not great :D

**Comment by DamianReeves** [comment]
I like option 3.
In addition I think it would be helpful to expose a configure that doesn't just take the plugin as input, but also all the virtual axis of that row, this would allow for customization of the project based on virtual axis, i.e.

```scala
...
jvmPlatform(...axes, (axes, project) => axes match {
  case (scalaversion::platform::myCustom::Nil, project) =>
     if(myCustom.name == "experimental") {
         project.dependsOn(experimentalProjRef)
    }
  case _ => project
})
