### ISSUE TITLE
Support Scala 3.1 in sandwich scenario

### ISSUE THREAD

**Issue by DamianReeves** [sbt/sbt-projectmatrix#66]
Now that Scala 3.1 is available we need to also support Scala 3.1 in the sandwich scenario

**Comment by DamianReeves** [comment]
Added a fix for this.

**Comment by DamianReeves** [comment]
@eed3si9n Any chance of getting a release with this merged.

**Comment by deusaquilus** [comment]
Currently sandwich pattern s are grueling to configure and manage for large projects with many build targets. This would be very useful!

**Comment by eed3si9n** [comment]
I just pushed the tag https://github.com/sbt/sbt-projectmatrix/releases/tag/v0.9.0. In theory, we'll have something up on Maven Central soon.
