### ISSUE TITLE
scala 3 `scalacOptions` behave like scala compiler version 2 in scala 3 projects

### ISSUE THREAD

**Issue by simlei** [sbt/sbt-projectmatrix#74]
Hi, 
I noticed, that in a sbt-projectmatrix project, I cannot properly use e.g. [`scalacOptions ++= Seq("-Xprint-inline")`](https://docs.scala-lang.org/scala3/guides/migration/options-new.html), which is a new flag for scalac / dotty in scala 3. I use `3.2.1-RC1`, but it's the same game for earlier scala 3 version.

It suffices to have a single `(projectMatrix in file("..."))` project that's aggregated in the root via `.aggregate(<projectmatrix>.projectRefs: _*)`. Projects that do not depend on it and use scala 3 are affected too, even if you do `<independentSub> / compile`.

The problem then manifests in task `compile`:

```
|| [error] bad option: '-Xprint-inline'
```

To reproduce:
- `lazy val sub1 = (projectMatrix in file("sub1"))`
- `  .jvmPlatform(scalaVersions = Seq("3.1.3", "2.12.16"))`
- in the root project, `.aggregate(sub1.projectRefs: _*)`
- in another project `lazy val sub2 = (project in file("sub2")).settings(scalaVersion := "3.1.3", scalacOptions += "-Xprint-inline")`
- ... do `sbt 'sub2 / clean;sub2 / compile'`
- get the `bad option` error

**Comment by keynmol** [comment]
Hmm. Isn't it Scala 2 complaining about the bad option? Because the scalacOptions are duplicated to all projects in the matrix, so your 2.12 build receives it as well.

Message seems to match:

```
/v/f/m/d/T/tmp.veUJYXKZ > scli test.scala -O -Xprint-inline
Compiling project (Scala 3.2.0, JVM)
Compiled project (Scala 3.2.0, JVM)
[error]  No main class found

/v/f/m/d/T/tmp.veUJYXKZ > scli test.scala -O -Xprint-inline -S 2
Compiling project (Scala 2.13.8, JVM)
Error: bad option: '-Xprint-inline'
Error compiling project (Scala 2.13.8, JVM)
Compilation failed
```

**Comment by simlei** [comment]
I suppose it could be the case. But I can't explain then, while in the same `sub2 / compile` run where the error message appears, scala-3-only sources are built successfully (indented syntax, etc etc). `show sub2 / scalaVersion` yields `3.1.3` also.

**Comment by keynmol** [comment]
I think there's conflated issues

sbt-projectmatrix will generate the following projects (run `projects` in SBT shell):

```
sub13
sub12_12
```

Your `sub2` is a separate, non projectmatrix project, where you set scala version to 3.1.3 yourself.

you can see what options any project has by running `show <projec>t/scalacOptions`. i.e. `show sub1/scalacOptions`

you can check which options each project has, and I would guess that sub12_12 will have the `-Xprint-inline` option and would fail to compile.

**Comment by simlei** [comment]
Your first reply was spot on. I had to switch on the scala version in my settings to only include the scala3 options when the version is a 3 version :sad:
sorry for the mixup. I'll close this. Many thanks for the assistance!
