### ISSUE TITLE
Jar Files in lib Folder Not Recognized

### ISSUE THREAD

**Issue by kijuky** [sbt/sbt-projectmatrix#90]
### Description:
Jar files within the `lib` folder are not recognized using the sbt-projectmatrix plugin.  
about lib folder: https://www.scala-sbt.org/1.x/docs/Library-Dependencies.html#Unmanaged+dependencies

### Reproduction:
A reproduction project can be found here: [Reproduction Project](https://github.com/kijuky/sbt-projectmatrix-lib)

### Steps to Reproduce:
1. Clone the reproduction project.
2. Follow the steps outlined in the project's README to reproduce the issue.

### Expected Behavior:
Jar files within the `lib` folder should be recognized and utilized by sbt-projectmatrix.

### Actual Behavior:
The jar files are not recognized by sbt-projectmatrix.

### Additional Information:
- This issue affects the functionality and usability of sbt-projectmatrix.
- Further investigation and resolution are required.

**Comment by eed3si9n** [comment]
Thanks for the report!

Probably relevant area:
https://github.com/sbt/sbt-projectmatrix/blob/458a172b8f3b5d4785af7cf43880e8d31b2e9245/src/main/scala/sbt/internal/ProjectMatrix.scala#L276-L285

in `makeSources` we add the source directories, but I'm not dealing with the `unmanagedBase`.
